version: "3"
services:
    postgres:
        container_name: postgres
        build:
            context: .
            dockerfile: postgres.Dockerfile
        ports: # Bind database to the host, to be able to enter the database.
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: password
            DATABASE_USERNAME: admin_db
            DATABASE_PASSWORD: Adm1n_d4ta
    tomcat:
        depends_on: # The Tomcat server needs the database to work.
            - postgres
            # - smtp
        container_name: tomcat
        build: # Build the Dockerfile on this directory for this service
            context: .
            dockerfile: tomcat.Dockerfile
        ports: # The application is binding 8080 (Tomcat Default Port) of the container to 8000 of the host to be able to use the app on the host.
            - 8000:8080
        environment: 
            DATABASE_USERNAME_ENV: $${DATABASE_USERNAME}
            DATABASE_PASSWORD_ENV: $${DATABASE_PASSWORD}
            MAIL_USERNAME: $${MAIL_USERNAME}
            MAIL_PASSWORD: $${MAIL_PASSWORD}
