pipeline {
    agent any
    tools {
        maven 'maven'
        jdk 'jdk8'
    }
    stages {
        stage('Build') {
            steps {
                dir('mail2clients') {
                    // Run Maven on a Unix agent.
                    sh "mvn -Dmaven.test.failure.ignore=true clean package"
                }
            }
            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the war file.
                success {
                    junit '**/mail2clients/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'mail2clients/target/*.war'
                }
            }
        }
        stage('Local Deploy') {
            steps {
                dir('mail2clients') {
                    // Run the whole project in a clean way on the host machine
                    sh 'docker-compose down'
                    sh 'docker-compose up -d --build --remove-orphans -V'
                }
            }
        }
        stage('Deploy Artifact') {
            steps {
                withCredentials([file(credentialsId: 'settings.xml', variable: 'settings')]) {
                    dir('mail2clients') {
                        sh 'mvn clean deploy -Dmaven.test.skip=true -s $settings'
                    }
                }
            }
        }
    }
}
